### ISSUE TITLE
Check for existing accounts for account creation and login

### ISSUE THREAD

**Issue by Ben-Wolf** [Ben-Wolf/Mergeable#22]
After the database is set up:
- [ ] make sure the account exists when logging in.
- [ ] make sure password and email match when logging in.
- [ ] make sure the account doesn't exist when creating an account.

Check by e-mail.

**Comment by evajiang322** [comment]
Mostly done.
mongoose promises library has been deprecated -> plug in our own library
Looking to also notify user of account errors.. Current implementation simply uses the console
