### ISSUE TITLE
Only one person can use Mergeable at a time

### ISSUE THREAD

**Issue by Ben-Wolf** [Ben-Wolf/Mergeable#53]
the way the sessions work, I can't simulate two being logged in. Having the acc global variable is bad news.

**Comment by evajiang322** [comment]
Try to use req.user to get the current session's user instead of the acc variable.

**Comment by Ben-Wolf** [comment]
Damn Eva, you right. (sit down... be humble)
Also learned how to $post :+1:

Resolved in https://github.com/Ben-Wolf/Mergeable/commit/535e1e750641531d43b6db093eeab5264c028aad
